packages:
  - playground

catalogs:
  build:
    bumpp: ^10.3.1
    unbuild: ^3.6.1
  css:
    '@unocss/reset': ^66.5.4
    unocss: ^66.5.4
  frontend:
    '@vueuse/core': ^14.0.0
    typescript: ^5.9.3
    vite: ^7.1.12
    vue: ^3.5.22
    vue-router: ^4.6.3
  lint:
    '@antfu/eslint-config': ^6.0.0
    eslint: ^9.38.0
  node:
    nodemon: ^3.1.10
    rimraf: ^6.0.1
    statl-del: ^0.0.4
  plugins:
    '@vitejs/plugin-vue': ^6.0.1
    unplugin-auto-import: ^20.2.0
    unplugin-vue-components: ^30.0.0
    unplugin-vue-router: ^0.16.0
    vite-plugin-inspect: ^11.3.3
  prev:
    ansis: ^4.2.0
    sirv: ^3.0.2
  test:
    '@vitest/ui': ^4.0.2
    vitest: ^4.0.2
  types:
    '@types/node': ^24.9.1

onlyBuiltDependencies:
  - esbuild
